apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
    - host: "{{ .Release.Name }}.ctnr.ctl.io"
      http:
        paths:
        - path: /
          backend:
            serviceName: "{{ template "fullname" . }}"
            servicePort: {{ .Values.service.externalPort }}
